### ISSUE TITLE
Incompatible types Region and Rectangle!int

### ISSUE THREAD

**Issue by BlackEdder** [cairoD/cairoD#21]
After applying #20 and trying to test the first example I get the following errors:
../../.dub/packages/cairod-master/src/cairo/cairo.d(5819): Error: 'region += rect2' is not a scalar, it is a Region
../../.dub/packages/cairod-master/src/cairo/cairo.d(5819): Error: incompatible types for
((region) += (rect2)): 'Region' and 'Rectangle!int'
../../.dub/packages/cairod-master/src/cairo/cairo.d(5833): Error: function cairo.cairo.ClipRange.opIndex (int i) is not callable using argument types (ulong)

**Comment by jpf91** [comment]
Hmm, now I'm not sure if this was ever fixed but I don't have any unpublished code anymore...

Which example produced this error? https://github.com/cairoD/cairoD/tree/master/example/1 ?
Can you still reproduce this?

**Comment by BlackEdder** [comment]
Good question :) I guess it would have been example 1 (first example). Just tried to run it and it worked perfectly. Guess we can close this for now.
