### ISSUE TITLE
Issues with dub package

### ISSUE THREAD

**Issue by JakobOvrum** [cairoD/cairoD#28]
On Windows, CairoD seems to depend on the Windows API bindings. This is not reflected in the dub package which consequently does not compile on Windows.

(Might also be a good time to start versioning, as depending on ~master is deprecated)

**Comment by jpf91** [comment]
The winapi headers will be included the next druntime release. So once the next release is available we'll simply have to update the imports and maybe some code and we're done.

**Comment by Robert-M-Muench** [comment]
@jpf91 I'm currently trying to get CairoD up and running on Win64. I have Cairo compiled. So, I'm a bit confused now what to do with CairoD. IIRC DMD has the windows API header stuff on board already. Or what is missing?

IMO the CairoD Linux focus needs to be encapsulated better and a Windows environment added.

**Comment by jpf91** [comment]
>  I'm currently trying to get CairoD up and running on Win64. I have Cairo compiled. So, I'm a bit confused now what to do with CairoD.

As long as you don't need windows specific features (`Win32Surface` and `Win32Font`) you can just use cairoD with dub like any other dub package*. The 'build script' is actually not tested on windows yet. if it doesn't work, use the `stlib-minimal` dub configuration for cairoD.

(*) And you have to figure out how to link your C cairo library on 64 bit windows. IIRC you need an import library for cairo. It's the same process as for any other C DLL.

> IIRC DMD has the windows API header stuff on board already. Or what is missing?

One example is `LOGFONTW`, which is not in the winapi bindings shipped with dmd. But it should be available in the next dmd release. These defines are only required when using `Win32Surface` or `Win32Font` features. As long as you only use the core subset, cairo(D) is very portable.

> IMO the CairoD Linux focus needs to be encapsulated better and a Windows environment added.

That's correct. I'll have to make sure the build scripts work well on windows and maybe we could provide precompiled cairo libraries and import libraries as well. Some 'Getting started' section in the README might be useful as well.

**Comment by jpf91** [comment]
cairoD should work fine on windows now. We support using the `windows-headers` package for older compilers and `core.sys.windows` should work for all 2.070+ compilers when using `version=CairoWindowsDruntime`. I've also included DLLs and import libraries to make life easier for windows users. The standard examples now work fine on windows.

The windows advanced examples might need some more fixes, but this is low priority. If somebody wants to fix these, please provide pull requests :-)
