### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by BlackEdder** [cairoD/cairoD#31]
@jpf91 Is anyone still maintaining this? I'm considering forking it, just to solve issues #30 and #29, but would of course rather it staying in the old familiar place.

**Comment by jpf91** [comment]
It's not really maintained, whenever I want to work on cairoD again something else intervenes :-(

I've moved cairoD to https://github.com/cairoD/cairoD . I can now add you to the cairoD organization if you want to help.

**Comment by BlackEdder** [comment]
Thanks @jpf91. I'd be happy to help where possible. Probably won't have time to actually add features, but should be able to help with maintenance related tasks.

**Comment by jpf91** [comment]
> but should be able to help with maintenance related tasks.

Great. I probably won't add new features either, but we should probably make sure cairoD compiles with new DMD versions, etc. Might also be useful to set up CI with travis CI and probably use some nicer documentation generator at some point.
