### ISSUE TITLE
Pass compiler to prebuild command/compiler dependend prebuild command

### ISSUE THREAD

**Issue by BlackEdder** [cairoD/cairoD#32]
Currently the prebuild command depends on rdmd, which it needs to build configure.d. A possible alternative option is to have different prebuildcommands depended on which compiler is being used:

Disadvantage of having different prebuildcommands is that we need to maintain them. Disadvantage of current approach is that every project depending on cairoD and using travis, will need to adapt their travis script to install rdmd.

Quote from Sonke:
There are DC and DC_BASE environment variables available, DC is
the binary name, as passed to --compiler and DC_BASE is the base
name of the compiler (e.g. "dmd" or "ldc").

Another possibility is to use a platform specifier for each compiler:
"preBuildCommands-dmd": [...].

**Comment by jpf91** [comment]
I'll have a look at this later this week. I think I'll just use the `preBuildCommands-*` option.

There's still one small problem: For cross-compiling this still won't work. `$DC` is a cross compiler in that case and can't be used to compile D code for the current machine. To make cross-compiling work we probably have to include shell/.bat scripts and try to detect a compiler which can compile for the current machine. But I'll probably just ignore cross-compiler support for now.

**Comment by jpf91** [comment]
Thinking about this some more I've switched to version-based configuration instead. It just works better with dub. Using a `configure` script means we have to care about many corner cases (cross-compiling, what is the correct C compiler on windows, what is the correct build compiler/rdmd/...).

The only problems with version based approaches are:
* Must always pass the `-version` parameter for all cairoD files and all user files. However, dub takes care of this, so this is not a problem.
* For shared libraries, we only configure the library once for all library users, so we should use the maximum supported functionality. However, shared libraries are not wide-spread in D yet and probably not fully supported in dub, so this is no big problem.

I'll still have to test this on windows before closing this bug report.

**Comment by jpf91** [comment]
Should be fixed. If there are no further issues with the build system I'll release a `0.0.1` version.
